/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-11-13 07:28:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.CHAPTER10;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import my.model.*;
import my.dao.*;
import java.sql.*;
import my.util.*;
import java.util.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/KPU_JSP2/ws/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/1023/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1492563438000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("my.model");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("my.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("my.dao");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>고객등록 신청서</title>\r\n");
      out.write("<link href=\"design.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".bigimage {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\theight: 370px;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("\tmargin-left: 30px;\r\n");
      out.write("}\r\n");
      out.write(".itemdetail {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\theight: 370px;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("\tmargin-left: 30px;\r\n");
      out.write("\tpadding-top: 30px;\r\n");
      out.write("\tpadding-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"page_header\">\r\n");
      out.write("\t\t<div class=\"toplogo\"><a href=\"#\"><img src=\"images/top_logo.jpg\" width=\"276\" height=\"40\" alt=\"beautifullife\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        <div class=\"topnav\">\r\n");
      out.write("        \t<ul>\r\n");
      out.write("            \t<li><a href=\"#\"><img src=\"images/top_menu1.jpg\" width=\"72\" height=\"24\" alt=\"ArtStory\"></a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/top_menu2.jpg\" width=\"76\" height=\"24\" alt=\"ArtStory\"></a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/top_menu3.jpg\" width=\"64\" height=\"24\" alt=\"ArtStory\"></a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/top_menu4.jpg\" width=\"134\" height=\"24\" alt=\"ArtStory\"></a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/top_menu5.jpg\" width=\"99\" height=\"24\" alt=\"ArtStory\"></a></li>\r\n");
      out.write("                <li><a href=\"#\"><img src=\"images/top_menu6.jpg\" width=\"52\" height=\"24\" alt=\"ArtStory\"></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("\t<div class=\"page_subimg\">\r\n");
      out.write("\t\t<div class=\"subimgline\"></div>\r\n");
      out.write("        <div class=\"subimg\">\r\n");
      out.write("        \t<div id=\"apDivSubimg\"></div>\r\n");
      out.write("       \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \t<div class=\"page_content\">\r\n");
      out.write("    \t<div class=\"leftmenu\">\r\n");
      out.write("   \t    \t<img src=\"images/left_title.jpg\" width=\"152\" height=\"24\" alt=\"membership\"> \r\n");
      out.write("        \t<ul>\r\n");
      out.write("            \t<li></li>\r\n");
      out.write("            \t<li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("                <li><a href=\"#\">아이디찾기</a></li>\r\n");
      out.write("                <li><a href=\"#\">비번찾기</a></li>\r\n");
      out.write("                <li><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("                <li><a href=\"#\">1:1문의하기</a></li>\r\n");
      out.write("                <li><a href=\"#\">질문내역</a></li>\r\n");
      out.write("                <li><a href=\"#\">후기내역</a></li>\r\n");
      out.write("                <li><a href=\"#\">쿠폰내역</a></li>\r\n");
      out.write("                <li><a href=\"#\">적립금내역</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"rightcon\">\r\n");
      out.write("        ");

        	int movieId=Integer.parseInt(request.getParameter("movieId"));
        	int amount=Integer.parseInt(request.getParameter("amount"));
        	Cart cart=new Cart();//기본생성자와 setter 이용해서 객체생성 or 파라미터 생성자 이용
        	cart.setMovieId(movieId);
        	cart.setAmount(amount);
        	Integer movieCount=(Integer)session.getAttribute("movieCount");//int는 데이터타입 Integer은 클래스 movieCount는 객체
        	if(movieCount==null)
        		movieCount=new Integer(0);
        	if(movieId!=0){
        		movieCount=new Integer(movieCount.intValue()+1);
        		session.setAttribute("movieCount", movieCount);
        		session.setAttribute("movie"+movieCount, cart);//the end
        	}	
        
      out.write("\r\n");
      out.write("        \t<img src=\"images/title1.jpg\" width=\"464\" height=\"58\" alt=\"고객등록\">\r\n");
      out.write("            <div class=\"tablestyle\">\r\n");
      out.write("            \t카트담기가 완료되었습니다. 바로 구매하시겠습니까? \r\n");
      out.write("            \t<input type=\"button\" onClick=\"location.href='cartpurchase.jsp'\" value=\"바로구매\"/>\r\n");
      out.write("            \t<input type=\"button\" onClick=\"location.href='movieCatalog.jsp'\" value=\"리스트가기\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
