/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-11-24 15:48:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modifyForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/KPU_JSP2/ws/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1542517944158L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>게시글 수정하기</title>\r\n");
      out.write("<link href=\"boardlayout.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#apDiv2 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 241px;\r\n");
      out.write("\ttop: 323px;\r\n");
      out.write("\twidth: 766px;\r\n");
      out.write("\theight: 515px;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\tvisibility: visible;\r\n");
      out.write("\tborder: medium solid #000;\r\n");
      out.write("\tfont-size: 24px;\r\n");
      out.write("\tpadding-left: 40px;\r\n");
      out.write("}\r\n");
      out.write("@charset \"utf-8\";\r\n");
      out.write("#wrap {\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\twidth: 1024px;\r\n");
      out.write("\tmargin-left: 100px;\r\n");
      out.write("\tbackground-color: #FFF;\r\n");
      out.write("\tbackground-image: none;\r\n");
      out.write("}\r\n");
      out.write("#page_header {\r\n");
      out.write("\theight: 140px;\r\n");
      out.write("\twidth: 1024px;\r\n");
      out.write("\tborder: thick solid #000;\r\n");
      out.write("}\r\n");
      out.write(".header_logo {\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\tmargin-top: 40px;\r\n");
      out.write("\tfont-size: 36pt;\r\n");
      out.write("\tfont-family: \"함초롬돋움\";\r\n");
      out.write("\tfont-style: normal;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: #FFF;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin-right: 190px;\r\n");
      out.write("}\r\n");
      out.write("#page_main {\r\n");
      out.write("\theight: 800px;\r\n");
      out.write("\twidth: 1024px;\r\n");
      out.write("}\r\n");
      out.write("#page_main table {\r\n");
      out.write("\tbackground-color: #FCC;\r\n");
      out.write("\tborder: thin solid #000;\r\n");
      out.write("}\r\n");
      out.write("#page_main table {\r\n");
      out.write("\tborder: thin solid #000;\r\n");
      out.write("}\r\n");
      out.write(".write {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tfont-family: \"함초롬돋움\";\r\n");
      out.write("\tfont-size: 14pt;\r\n");
      out.write("}\r\n");
      out.write("#login {\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\tmargin-top: 70px;\r\n");
      out.write("\tmargin-left: 200px;\r\n");
      out.write("\tborder: thin none #FFF;\r\n");
      out.write("}\r\n");
      out.write("#apDiv1 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 407px;\r\n");
      out.write("\ttop: 240px;\r\n");
      out.write("\twidth: 415px;\r\n");
      out.write("\theight: 288px;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("\tborder: medium solid #000;\r\n");
      out.write("\tbackground-color: #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".loginlogo {\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("#logo {\r\n");
      out.write("\theight: 71px;\r\n");
      out.write("\twidth: 230px;\r\n");
      out.write("\tmargin-top: 40px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("  <div id=\"page_main\"><div id=\"apDiv2\">\r\n");
      out.write("  <p align=\"center\"><strong>게시글 수정하기</strong></p>\r\n");
      out.write("  <form action=\"modify.do\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modReq.articleNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    <p align=\"center\">\r\n");
      out.write("    <p align=\"left\"><strong>번호 :</strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modReq.articleNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("         \r\n");
      out.write("<label for=\"title\">\r\n");
      out.write("  <br />\r\n");
      out.write("  <br />\r\n");
      out.write("</label>\r\n");
      out.write("<strong>제목</strong>\r\n");
      out.write("    <p align=\"left\">\r\n");
      out.write("      <input type=\"text\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modReq.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t  ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  </p>\r\n");
      out.write("    <p align=\"center\">&nbsp;</p>\r\n");
      out.write("    <p align=\"left\"><strong>내용</strong></p>\r\n");
      out.write("    <p align=\"left\">\r\n");
      out.write("      <label for=\"content\"></label>\r\n");
      out.write("      <textarea name=\"content\" cols=\"45\" rows=\"5\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modReq.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("    </p>\r\n");
      out.write("    <p align=\"center\">\r\n");
      out.write("      <input type=\"submit\" value=\"글 수정\" />\r\n");
      out.write("    </p>\r\n");
      out.write("  </form></div></div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/view/modifyForm.jsp(111,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errors.title}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("제목을 입력하세요.");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
